<?php
$data = array (
  0 => 
  array (
    'cat_id' => '4',
    'cat_name' => '孝心攻略',
    'cat_type' => '1',
    'keywords' => '孝心攻略',
    'cat_desc' => '孝心攻略是告知客户怎样给老年人选购合适的商品',
    'sort_order' => '1',
    'show_in_nav' => '1',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '7',
  ),
  1 => 
  array (
    'cat_id' => '9',
    'cat_name' => '馨予建站的优点',
    'cat_type' => '1',
    'keywords' => '建站优点',
    'cat_desc' => '馨予建站的优点介绍',
    'sort_order' => '2',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '5',
    'aricle_num' => '5',
  ),
  2 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '3',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  4 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '6',
    'aricle_num' => '0',
  ),
  5 => 
  array (
    'cat_id' => '14',
    'cat_name' => '关于孝心说',
    'cat_type' => '5',
    'keywords' => '孝心说简介',
    'cat_desc' => '关于孝心说',
    'sort_order' => '1',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  6 => 
  array (
    'cat_id' => '8',
    'cat_name' => '新手上路',
    'cat_type' => '5',
    'keywords' => '新手上路',
    'cat_desc' => '新手上路',
    'sort_order' => '2',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  7 => 
  array (
    'cat_id' => '15',
    'cat_name' => '常见问题',
    'cat_type' => '5',
    'keywords' => '常见问题',
    'cat_desc' => '常见问题',
    'sort_order' => '3',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  8 => 
  array (
    'cat_id' => '16',
    'cat_name' => '配送说明',
    'cat_type' => '5',
    'keywords' => '配送说明',
    'cat_desc' => '配送说明',
    'sort_order' => '4',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  9 => 
  array (
    'cat_id' => '6',
    'cat_name' => '支付方式',
    'cat_type' => '5',
    'keywords' => '支付方式',
    'cat_desc' => '支付方式',
    'sort_order' => '5',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  10 => 
  array (
    'cat_id' => '7',
    'cat_name' => '售后服务',
    'cat_type' => '5',
    'keywords' => '服务支持',
    'cat_desc' => '客户凡是在馨予建站买的模板都享受售后免费服务，',
    'sort_order' => '6',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  11 => 
  array (
    'cat_id' => '10',
    'cat_name' => 'SEO知识',
    'cat_type' => '1',
    'keywords' => 'SEO知识',
    'cat_desc' => '如果一个网站没有seo优化，那就意味着这个网站要完蛋！馨予建站为了改善！特意seo优化',
    'sort_order' => '1',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  12 => 
  array (
    'cat_id' => '11',
    'cat_name' => '设计制作',
    'cat_type' => '1',
    'keywords' => '设计制作',
    'cat_desc' => '设计制作',
    'sort_order' => '2',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  13 => 
  array (
    'cat_id' => '12',
    'cat_name' => '使用维护',
    'cat_type' => '1',
    'keywords' => '使用维护',
    'cat_desc' => '使用馨予建站版ecshop 有利用维护',
    'sort_order' => '3',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  14 => 
  array (
    'cat_id' => '13',
    'cat_name' => '经营项目',
    'cat_type' => '1',
    'keywords' => '经营项目',
    'cat_desc' => '经营项目',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  15 => 
  array (
    'cat_id' => '5',
    'cat_name' => '购站指南',
    'cat_type' => '1',
    'keywords' => '购站指南',
    'cat_desc' => '馨予建站购站指南主要是介绍客户在购买网站的一些主要流程及方法',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
);
?>