<?php
$data = array (
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '饮食营养',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '76',
    'name' => '饮食营养',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '养生食品',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '1',
    'has_children' => '11',
    'goods_num' => 0,
    'level' => 1,
    'id' => '78',
    'name' => '养生食品',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '79',
    'name' => '茶叶',
  ),
  163 => 
  array (
    'cat_id' => '163',
    'cat_name' => '五谷杂粮',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '163',
    'name' => '五谷杂粮',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '蜂蜜/蜂产品',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '81',
    'name' => '蜂蜜/蜂产品',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '人参',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '80',
    'name' => '人参',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => '无糖食品',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '162',
    'name' => '无糖食品',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '枸杞',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '82',
    'name' => '枸杞',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '阿胶',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '83',
    'name' => '阿胶',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '虫草',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => '虫草',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '枣',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '86',
    'name' => '枣',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '鹿茸',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '85',
    'name' => '鹿茸',
  ),
  161 => 
  array (
    'cat_id' => '161',
    'cat_name' => '苦荞茶',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '161',
    'name' => '苦荞茶',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '营养品',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '2',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 1,
    'id' => '77',
    'name' => '营养品',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '维生素',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '87',
    'name' => '维生素',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '蛋白质',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '88',
    'name' => '蛋白质',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '矿物质',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '90',
    'name' => '矿物质',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '胶原蛋白',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '91',
    'name' => '胶原蛋白',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '葡萄籽',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '89',
    'name' => '葡萄籽',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '左旋肉碱',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '92',
    'name' => '左旋肉碱',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '植物提取物',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '93',
    'name' => '植物提取物',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '益生菌',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '益生菌',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '牛初乳',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '94',
    'name' => '牛初乳',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '钙',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '152',
    'name' => '钙',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => '按功能',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '11',
    'goods_num' => 0,
    'level' => 1,
    'id' => '153',
    'name' => '按功能',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => '辅助降血脂',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '154',
    'name' => '辅助降血脂',
  ),
  158 => 
  array (
    'cat_id' => '158',
    'cat_name' => '辅助降血糖',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '158',
    'name' => '辅助降血糖',
  ),
  164 => 
  array (
    'cat_id' => '164',
    'cat_name' => '辅助降血压',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '164',
    'name' => '辅助降血压',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => '增加骨密度',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '155',
    'name' => '增加骨密度',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => '抗氧化',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '156',
    'name' => '抗氧化',
  ),
  157 => 
  array (
    'cat_id' => '157',
    'cat_name' => '增强免疫力',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '157',
    'name' => '增强免疫力',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => '祛黄褐斑',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '159',
    'name' => '祛黄褐斑',
  ),
  160 => 
  array (
    'cat_id' => '160',
    'cat_name' => '改善睡眠',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '160',
    'name' => '改善睡眠',
  ),
  165 => 
  array (
    'cat_id' => '165',
    'cat_name' => '补钙',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '165',
    'name' => '补钙',
  ),
  166 => 
  array (
    'cat_id' => '166',
    'cat_name' => '缓解疲劳',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '166',
    'name' => '缓解疲劳',
  ),
  167 => 
  array (
    'cat_id' => '167',
    'cat_name' => '通便',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '167',
    'name' => '通便',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '按摩保健',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '按摩保健',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '按摩',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '97',
    'name' => '按摩',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '按摩椅',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '100',
    'name' => '按摩椅',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '按摩器',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '101',
    'name' => '按摩器',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '按摩棒/捶',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '按摩棒/捶',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '足部保健',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '99',
    'name' => '足部保健',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '足疗机',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '110',
    'name' => '足疗机',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '足浴盆',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '足浴盆',
  ),
  168 => 
  array (
    'cat_id' => '168',
    'cat_name' => '家庭健身',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '168',
    'name' => '家庭健身',
  ),
  169 => 
  array (
    'cat_id' => '169',
    'cat_name' => '跑步机',
    'measure_unit' => '',
    'parent_id' => '168',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '169',
    'name' => '跑步机',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => '踏步机',
    'measure_unit' => '',
    'parent_id' => '168',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '170',
    'name' => '踏步机',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => '健身球',
    'measure_unit' => '',
    'parent_id' => '168',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '171',
    'name' => '健身球',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '理疗',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '98',
    'name' => '理疗',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '骨质增生理疗',
    'measure_unit' => '',
    'parent_id' => '98',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '骨质增生理疗',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '风湿性关节炎症理疗',
    'measure_unit' => '',
    'parent_id' => '98',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '风湿性关节炎症理疗',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '颈椎理疗',
    'measure_unit' => '',
    'parent_id' => '98',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '颈椎理疗',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '肩周炎理疗',
    'measure_unit' => '',
    'parent_id' => '98',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '肩周炎理疗',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '腰椎理疗',
    'measure_unit' => '',
    'parent_id' => '98',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '105',
    'name' => '腰椎理疗',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '健康检测',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '111',
    'name' => '健康检测',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '血压',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '血压',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '血压仪',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '116',
    'name' => '血压仪',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '血糖',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '113',
    'name' => '血糖',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '试纸',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '118',
    'name' => '试纸',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '血糖仪',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '117',
    'name' => '血糖仪',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '心率',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '114',
    'name' => '心率',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '心率表',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '119',
    'name' => '心率表',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '115',
    'name' => '其他',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '脂肪仪',
    'measure_unit' => '',
    'parent_id' => '115',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '121',
    'name' => '脂肪仪',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '计步器',
    'measure_unit' => '',
    'parent_id' => '115',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '计步器',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '体重秤',
    'measure_unit' => '',
    'parent_id' => '115',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '123',
    'name' => '体重秤',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '体温计',
    'measure_unit' => '',
    'parent_id' => '115',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '120',
    'name' => '体温计',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '康复护理',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '124',
    'name' => '康复护理',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '家庭医疗',
    'measure_unit' => '',
    'parent_id' => '124',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '137',
    'name' => '家庭医疗',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '制氧机',
    'measure_unit' => '',
    'parent_id' => '137',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '139',
    'name' => '制氧机',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '吸痰器',
    'measure_unit' => '',
    'parent_id' => '137',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '146',
    'name' => '吸痰器',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '雾化仪',
    'measure_unit' => '',
    'parent_id' => '137',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => '雾化仪',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '呼吸机',
    'measure_unit' => '',
    'parent_id' => '137',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '呼吸机',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => '止鼾器',
    'measure_unit' => '',
    'parent_id' => '137',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '147',
    'name' => '止鼾器',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '净化器',
    'measure_unit' => '',
    'parent_id' => '137',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '144',
    'name' => '净化器',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '经络仪',
    'measure_unit' => '',
    'parent_id' => '137',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '141',
    'name' => '经络仪',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => '助听器',
    'measure_unit' => '',
    'parent_id' => '137',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '145',
    'name' => '助听器',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => '血氧仪',
    'measure_unit' => '',
    'parent_id' => '137',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '142',
    'name' => '血氧仪',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '出行代步',
    'measure_unit' => '',
    'parent_id' => '124',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '125',
    'name' => '出行代步',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '手杖',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '129',
    'name' => '手杖',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '助行器',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '131',
    'name' => '助行器',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '拐杖',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '130',
    'name' => '拐杖',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '轮椅',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '127',
    'name' => '轮椅',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '代步车',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '128',
    'name' => '代步车',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '起居',
    'measure_unit' => '',
    'parent_id' => '124',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '126',
    'name' => '起居',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '坐厕椅',
    'measure_unit' => '',
    'parent_id' => '126',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '134',
    'name' => '坐厕椅',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '护理床',
    'measure_unit' => '',
    'parent_id' => '126',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '132',
    'name' => '护理床',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '防褥疮垫',
    'measure_unit' => '',
    'parent_id' => '126',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '133',
    'name' => '防褥疮垫',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '电子电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '135',
    'name' => '电子电器',
  ),
  177 => 
  array (
    'cat_id' => '177',
    'cat_name' => '日常电器',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '177',
    'name' => '日常电器',
  ),
  181 => 
  array (
    'cat_id' => '181',
    'cat_name' => '榨汁机',
    'measure_unit' => '',
    'parent_id' => '177',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '181',
    'name' => '榨汁机',
  ),
  178 => 
  array (
    'cat_id' => '178',
    'cat_name' => '煎药壶',
    'measure_unit' => '',
    'parent_id' => '177',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '178',
    'name' => '煎药壶',
  ),
  182 => 
  array (
    'cat_id' => '182',
    'cat_name' => '养生壶',
    'measure_unit' => '',
    'parent_id' => '177',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '182',
    'name' => '养生壶',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => '加湿器',
    'measure_unit' => '',
    'parent_id' => '177',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '179',
    'name' => '加湿器',
  ),
  180 => 
  array (
    'cat_id' => '180',
    'cat_name' => '豆浆机',
    'measure_unit' => '',
    'parent_id' => '177',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '180',
    'name' => '豆浆机',
  ),
  172 => 
  array (
    'cat_id' => '172',
    'cat_name' => '数码产品',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '172',
    'name' => '数码产品',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => '老年手机',
    'measure_unit' => '',
    'parent_id' => '172',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '173',
    'name' => '老年手机',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => '老年收音机',
    'measure_unit' => '',
    'parent_id' => '172',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '174',
    'name' => '老年收音机',
  ),
  176 => 
  array (
    'cat_id' => '176',
    'cat_name' => '老年扩音器',
    'measure_unit' => '',
    'parent_id' => '172',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '176',
    'name' => '老年扩音器',
  ),
  175 => 
  array (
    'cat_id' => '175',
    'cat_name' => '评书机',
    'measure_unit' => '',
    'parent_id' => '172',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '175',
    'name' => '评书机',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '日常用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '136',
    'name' => '日常用品',
  ),
  183 => 
  array (
    'cat_id' => '183',
    'cat_name' => '老年服饰',
    'measure_unit' => '',
    'parent_id' => '136',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '183',
    'name' => '老年服饰',
  ),
  184 => 
  array (
    'cat_id' => '184',
    'cat_name' => '保暖内衣',
    'measure_unit' => '',
    'parent_id' => '183',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '184',
    'name' => '保暖内衣',
  ),
  185 => 
  array (
    'cat_id' => '185',
    'cat_name' => '老人鞋',
    'measure_unit' => '',
    'parent_id' => '183',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '185',
    'name' => '老人鞋',
  ),
  186 => 
  array (
    'cat_id' => '186',
    'cat_name' => '自发热衣服',
    'measure_unit' => '',
    'parent_id' => '183',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '186',
    'name' => '自发热衣服',
  ),
  191 => 
  array (
    'cat_id' => '191',
    'cat_name' => '图书音像',
    'measure_unit' => '',
    'parent_id' => '136',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '191',
    'name' => '图书音像',
  ),
  192 => 
  array (
    'cat_id' => '192',
    'cat_name' => '刮痧按摩书',
    'measure_unit' => '',
    'parent_id' => '191',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '192',
    'name' => '刮痧按摩书',
  ),
  194 => 
  array (
    'cat_id' => '194',
    'cat_name' => '穴位书',
    'measure_unit' => '',
    'parent_id' => '191',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '194',
    'name' => '穴位书',
  ),
  193 => 
  array (
    'cat_id' => '193',
    'cat_name' => '糖尿病书',
    'measure_unit' => '',
    'parent_id' => '191',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '193',
    'name' => '糖尿病书',
  ),
  187 => 
  array (
    'cat_id' => '187',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '136',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '187',
    'name' => '其他',
  ),
  188 => 
  array (
    'cat_id' => '188',
    'cat_name' => '放大镜指甲刀',
    'measure_unit' => '',
    'parent_id' => '187',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '188',
    'name' => '放大镜指甲刀',
  ),
  189 => 
  array (
    'cat_id' => '189',
    'cat_name' => '颈椎枕',
    'measure_unit' => '',
    'parent_id' => '187',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '189',
    'name' => '颈椎枕',
  ),
  190 => 
  array (
    'cat_id' => '190',
    'cat_name' => '腰椎枕',
    'measure_unit' => '',
    'parent_id' => '187',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '190',
    'name' => '腰椎枕',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '孝心礼品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '138',
    'name' => '孝心礼品',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '礼包',
    'measure_unit' => '',
    'parent_id' => '138',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '148',
    'name' => '礼包',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '养生礼包',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '149',
    'name' => '养生礼包',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '健康礼包',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '150',
    'name' => '健康礼包',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '益寿礼包',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '151',
    'name' => '益寿礼包',
  ),
);
?>